messages:
  hello: "+hello world"
  some_data: "+some data"
  neg: "-123neg"

actions:
  - message: hello
    action: Recv
    wait_for: some_data
  - message: neg
    action: Recv
  - message: some_data
    action: Send
